# Generated by Django 2.2.5 on 2019-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customercity_factorders_geolocationcity_orderitems_orderpayments_orderreviews_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('date', models.FloatField(max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderamount',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
