# Generated by Django 2.2.5 on 2019-10-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191029_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypurchase',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
