# Generated by Django 2.1.13 on 2019-11-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_todayorderdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.FloatField(max_length=20)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TodayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.FloatField(max_length=20)),
                ('amountValue', models.FloatField(default=0)),
                ('revenueValue', models.FloatField(default=0)),
            ],
        ),
    ]
